#!/bin/sh

UNIONDIR=`mktemp -d`
RWDIR=$HOME/.gog/masterofmagic
RODIR=/opt/gog/master_of_magic/base

mkdir -p $RWDIR
unionfs -o cow ${RWDIR}=RW:${RODIR}=RO $UNIONDIR

cd $UNIONDIR
dosbox -conf dosboxMOM.conf
cd

sleep 1
fusermount -u $UNIONDIR
rmdir $UNIONDIR