#!/bin/sh

UNIONDIR=`mktemp -d`
RWDIR=$HOME/.gog/heroes_of_might_and_magic
RODIR=/opt/gog/heroes_of_might_and_magic/base

mkdir -p $RWDIR
unionfs -o cow -o uid=$UID ${RWDIR}=RW:${RODIR}=RO $UNIONDIR

cd $UNIONDIR
dosbox -conf /opt/gog/heroes_of_might_and_magic/dosbox/homm.conf
cd

sleep 1
fusermount -u $UNIONDIR
rmdir $UNIONDIR
