#!/bin/sh

UNIONDIR=`mktemp -d --tmpdir=$HOME/.gog`
RWDIR=$HOME/.gog/stronghold
RODIR=/opt/gog/stronghold/base

mkdir -p $RWDIR
unionfs -o cow ${RWDIR}=RW:${RODIR}=RO $UNIONDIR

export WINEARCH=win32
export WINEPREFIX=$UNIONDIR
cd $WINEPREFIX/drive_c/Program\ Files/GOG.com/Stronghold
wine Stronghold.exe
cd

# None of this works yet
sleep 1
fusermount -u $UNIONDIR
rmdir $UNIONDIR
