#!/bin/sh

UNIONDIR=`mktemp -d`
RWDIR=$HOME/.gog/gemini_rue
RODIR=/opt/gog/gemini_rue/base

mkdir -p $RWDIR
unionfs -o cow ${RWDIR}=RW:${RODIR}=RO $UNIONDIR

cd $UNIONDIR
ags
cd

sleep 1
fusermount -u $UNIONDIR
rmdir $UNIONDIR
